# Generated by Django 5.0 on 2024-02-21 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakat_typee', models.CharField(choices=[('gold', 'Gold'), ('money', 'Money'), ('plant', 'plant'), ('silver', 'Silver'), ('livestock', 'Livestock')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockZakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('C', 'بقرة'), ('S', 'شاة'), ('G', 'ابل')], max_length=1)),
                ('count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverZakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Price_of_gram_of_silver', models.DecimalField(decimal_places=3, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('year_type', models.CharField(choices=[('M', 'ميلادي'), ('H', 'هجري')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zakat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakatapp.zakattype')),
            ],
        ),
        migrations.CreateModel(
            name='PlantZakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Irrigation_method', models.CharField(choices=[('Watering_at_a_cost', 'تسقى بتكلفه'), ('Watered_without', 'تسقى بدون تكلفة')], max_length=20)),
                ('Plants_per_kilo', models.DecimalField(decimal_places=3, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('zakatWeight', models.DecimalField(decimal_places=3, max_digits=20)),
                ('year_harvested', models.DateField()),
                ('Price_per_kilo', models.DecimalField(decimal_places=3, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zakat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakatapp.zakattype')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyZakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('year_type', models.CharField(choices=[('M', 'ميلادي'), ('H', 'هجري')], max_length=1)),
                ('silver_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('money', models.DecimalField(decimal_places=3, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zakat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakatapp.zakattype')),
            ],
        ),
        migrations.CreateModel(
            name='GoldZakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=20)),
                ('gold_karat', models.CharField(choices=[('10', '10'), ('14', '14'), ('18', '18'), ('21', '21'), ('22', '22'), ('24', '24')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('year_type', models.CharField(choices=[('M', 'ميلادي'), ('H', 'هجري')], max_length=1)),
                ('Price_of_gram_of_gold', models.DecimalField(decimal_places=3, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zakat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakatapp.zakattype')),
            ],
        ),
    ]
